spring.application.name=springbootapp
spring.profiles.active=local
#server.port=8085

#spring.sql.init.platform=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/booking?currentSchema=expobook
#spring.jpa.hibernate.ddl-auto=create
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.hikari.leak-detection-threshold=60000
#spring.datasource.hikari.maximum-pool-size=1
#spring.datasource.driver-class-name=org.postgresql.Driver


spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://postges.postgres.database.azure.com:5432/postgres?user=postgres&password=Qazxsw@34rfv&sslmode=require
spring.jpa.hibernate.ddl-auto= update
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.hikari.leak-detection-threshold=60000
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
