spring.application.name=springbootapp
spring.profiles.active=local
#server.port=8085

#spring.sql.init.platform=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/booking?currentSchema=expobook
#spring.jpa.hibernate.ddl-auto=create
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.hikari.leak-detection-threshold=60000
#spring.datasource.hikari.maximum-pool-size=1
#spring.datasource.driver-class-name=org.postgresql.Driver


spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://postgress204.postgres.database.azure.com:5432/postgres?user=${DB_USERNAME}&password=${DB_PASSWORD}&sslmode=require
spring.jpa.hibernate.ddl-auto= update
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.leak-detection-threshold=60000
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.driver-class-name=org.postgresql.Driver
